version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "nataliagranato/go-crud-app:v1.0.0"
    ports:
      - "8080:8080"
    volumes:
      - sqlite_data:/data
    environment:
      - DB_PATH=/data/app.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  sqlite_data: